FROM python

WORKDIR /app

COPY . .

CMD ["python", "index.py"]


# 0.

# В терминале написать, чтобы создать контейнер:
# docker build .  
# либо
# docker build . -f Dockerfile

# 1.
# Подождать, пока не завершится сборка (например)
# [+] Building 42.8s (5/8)
# [+] Building 85.3s (5/8)

# 2.

# Затем написать:
# docker image ls
# Чтобы увидеть файл IMAGE ID для выполнения кода

# 3.

# Скорпируйте ID с IMAGE ID, затем написать:
# docker run `ID`

# 4. 
# Удалить все контейеры можно:
# docker system prune -a
