FROM python

WORKDIR /app

COPY . .

CMD ["python", "index.py"]


# 1.

# В терминале написать, чтобы создать контейнер:
# docker build .  
# либо
# docker build . -f Dockerfile.txt

# 2.

# Затем написать:
# docker image ls
# Чтобы увидеть файл IMAGE ID для выполнения кода

# 3.

# Скорпируйте ID с IMAGE ID, затем написать:
# docker run `ID`

# 4. 
# Удалить все контейеры можно:
# docker system prune -a
